const EmotionCalendario = () => {
    return(
        <table id="calendario-emotion">
            <thead>
                <tr>
                    <td>Seg</td>
                    <td>Ter</td>
                    <td>Qua</td>
                    <td>Qui</td>
                    <td>Sex</td>
                </tr>
            </thead>
            <tbody>
                <label>24/07/2023</label>
                <tr>
                    <td>😄</td>
                    <td>😄</td>
                    <td>😄</td>
                    <td>😢</td>
                    <td>😆</td>
                </tr>
                <label>17/07/2023</label>
                <tr>
                    <td>😡</td>
                    <td>😄</td>
                    <td>😡</td>
                    <td>😢</td>
                    <td>😆</td>
                </tr>
                <label>10/07/2023</label>
                <tr>
                    <td>😡</td>
                    <td>😡</td>
                    <td>😄</td>
                    <td>😢</td>
                    <td>😆</td>
                </tr>
                <label>03/07/2023</label>
                <tr>
                    <td>😡</td>
                    <td>😄</td>
                    <td>😄</td>
                    <td>😢</td>
                    <td>😆</td>
                </tr>
            </tbody>
        </table>
    )
}

export default EmotionCalendario